FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-runtime

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir datasets pandas scikit-learn transformers accelerate

# Copy training script
COPY train_transformer.py .

CMD ["python", "train_transformer.py"]
